/*
 * The MIT License
 *
 * Copyright 2017 Neel Patel.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui.gui.util;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Neel Patel
 */
public class ProgramDBHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgramDetailCreater
     */
    public ProgramDBHomePanel() {
        //creditErrLabel.setText("");
        initComponents();    
    }

    public JButton getAddProgramButton() {
        return addProgramButton;
    }

    public JButton getAddTestCaseButton() {
        return addTestCaseButton;
    }

    public JLabel getDatabaseLabel() {
        return databaseLabel;
    }

    public JButton getRemoveProgramButton() {
        return removeProgramButton;
    }

    public JButton getRemoveTestCaseButton() {
        return removeTestCaseButton;
    }

    public JButton getSelectDBButton() {
        return selectDBButton;
    }

    public JButton getShowProgramButton() {
        return showProgramButton;
    }

    public JButton getShowTestCaseButton() {
        return showTestCaseButton;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databaseLabel = new javax.swing.JLabel();
        selectDBButton = new javax.swing.JButton();
        showProgramButton = new javax.swing.JButton();
        addProgramButton = new javax.swing.JButton();
        addTestCaseButton = new javax.swing.JButton();
        showTestCaseButton = new javax.swing.JButton();
        removeProgramButton = new javax.swing.JButton();
        removeTestCaseButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(9, 238, 249));
        setToolTipText(""); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(100, 17));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        databaseLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        databaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        databaseLabel.setText("none");
        databaseLabel.setToolTipText("");
        databaseLabel.setName("creditLable"); // NOI18N

        selectDBButton.setBackground(new java.awt.Color(0, 0, 0));
        selectDBButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        selectDBButton.setForeground(new java.awt.Color(9, 238, 249));
        selectDBButton.setText("Select DataBase");
        selectDBButton.setBorder(null);

        showProgramButton.setBackground(new java.awt.Color(0, 0, 0));
        showProgramButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showProgramButton.setForeground(new java.awt.Color(9, 238, 249));
        showProgramButton.setBorder(null);
        showProgramButton.setLabel("Show all Programs");
        showProgramButton.setOpaque(false);

        addProgramButton.setBackground(new java.awt.Color(0, 0, 0));
        addProgramButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addProgramButton.setForeground(new java.awt.Color(9, 238, 249));
        addProgramButton.setBorder(null);
        addProgramButton.setLabel("Add new Program");
        addProgramButton.setOpaque(false);

        addTestCaseButton.setBackground(new java.awt.Color(0, 0, 0));
        addTestCaseButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addTestCaseButton.setForeground(new java.awt.Color(9, 238, 249));
        addTestCaseButton.setText("Add new Test Case");
        addTestCaseButton.setBorder(null);
        addTestCaseButton.setOpaque(false);
        addTestCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTestCaseButtonActionPerformed(evt);
            }
        });

        showTestCaseButton.setBackground(new java.awt.Color(0, 0, 0));
        showTestCaseButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showTestCaseButton.setForeground(new java.awt.Color(9, 238, 249));
        showTestCaseButton.setText("Show Test Case");
        showTestCaseButton.setBorder(null);
        showTestCaseButton.setOpaque(false);
        showTestCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTestCaseButtonActionPerformed(evt);
            }
        });

        removeProgramButton.setBackground(new java.awt.Color(0, 0, 0));
        removeProgramButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removeProgramButton.setForeground(new java.awt.Color(255, 102, 0));
        removeProgramButton.setText("Remove Program");
        removeProgramButton.setBorder(null);
        removeProgramButton.setOpaque(false);

        removeTestCaseButton.setBackground(new java.awt.Color(0, 0, 0));
        removeTestCaseButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removeTestCaseButton.setForeground(new java.awt.Color(255, 102, 0));
        removeTestCaseButton.setText("Remove Test Case");
        removeTestCaseButton.setBorder(null);
        removeTestCaseButton.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectDBButton)
                        .addGap(18, 18, 18)
                        .addComponent(databaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showProgramButton)
                            .addComponent(addTestCaseButton)
                            .addComponent(showTestCaseButton)
                            .addComponent(addProgramButton)
                            .addComponent(removeProgramButton)
                            .addComponent(removeTestCaseButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDBButton)
                    .addComponent(databaseLabel))
                .addGap(51, 51, 51)
                .addComponent(showProgramButton)
                .addGap(18, 18, 18)
                .addComponent(showTestCaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addProgramButton)
                .addGap(18, 18, 18)
                .addComponent(addTestCaseButton)
                .addGap(18, 18, 18)
                .addComponent(removeProgramButton)
                .addGap(18, 18, 18)
                .addComponent(removeTestCaseButton)
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addTestCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTestCaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTestCaseButtonActionPerformed

    private void showTestCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTestCaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showTestCaseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProgramButton;
    private javax.swing.JButton addTestCaseButton;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JButton removeProgramButton;
    private javax.swing.JButton removeTestCaseButton;
    private javax.swing.JButton selectDBButton;
    private javax.swing.JButton showProgramButton;
    private javax.swing.JButton showTestCaseButton;
    // End of variables declaration//GEN-END:variables
}
