/*
 * The MIT License
 *
 * Copyright 2017 Neel Patel.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui.gui.util;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Neel Patel
 */
public class TestDBHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgramDetailCreater
     */
    public TestDBHomePanel() {
        //creditErrLabel.setText("");
        initComponents();    
    }

    public JButton getAddProgramButton() {
        return showUserButton;
    }

//    public JButton getAddTestCaseButton() {
//        return addTestCaseButton;
//    }

    public JLabel getDatabaseLabel() {
        return databaseLabel;
    }

    public JButton getRemoveProgramButton() {
        return resetButton;
    }

//    public JButton getRemoveTestCaseButton() {
//        return removeTestCaseButton;
//    }

    public JButton getSelectDBButton() {
        return selectDBButton;
    }

    public JButton getShowProgramButton() {
        return popButton;
    }

    public JButton getShowTestCaseButton() {
        return showAllUserButton;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databaseLabel = new javax.swing.JLabel();
        selectDBButton = new javax.swing.JButton();
        popButton = new javax.swing.JButton();
        showUserButton = new javax.swing.JButton();
        showAllUserButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(9, 238, 249));
        setToolTipText(""); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(100, 17));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        databaseLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        databaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        databaseLabel.setText("none");
        databaseLabel.setToolTipText("");
        databaseLabel.setName("creditLable"); // NOI18N

        selectDBButton.setBackground(new java.awt.Color(0, 0, 0));
        selectDBButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        selectDBButton.setForeground(new java.awt.Color(9, 238, 249));
        selectDBButton.setText("Select DataBase");
        selectDBButton.setBorder(null);

        popButton.setBackground(new java.awt.Color(0, 0, 0));
        popButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        popButton.setForeground(new java.awt.Color(9, 238, 249));
        popButton.setText("Pop DataBase");
        popButton.setBorder(null);
        popButton.setOpaque(false);
        popButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popButtonActionPerformed(evt);
            }
        });

        showUserButton.setBackground(new java.awt.Color(0, 0, 0));
        showUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showUserButton.setForeground(new java.awt.Color(9, 238, 249));
        showUserButton.setText("Show User");
        showUserButton.setBorder(null);
        showUserButton.setOpaque(false);

        showAllUserButton.setBackground(new java.awt.Color(0, 0, 0));
        showAllUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showAllUserButton.setForeground(new java.awt.Color(9, 238, 249));
        showAllUserButton.setText("Show All User");
        showAllUserButton.setBorder(null);
        showAllUserButton.setOpaque(false);
        showAllUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllUserButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(0, 0, 0));
        resetButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 102, 0));
        resetButton.setText("Reset DataBase");
        resetButton.setBorder(null);
        resetButton.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectDBButton)
                        .addGap(18, 18, 18)
                        .addComponent(databaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popButton)
                            .addComponent(showAllUserButton)
                            .addComponent(showUserButton)
                            .addComponent(resetButton))
                        .addGap(0, 673, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDBButton)
                    .addComponent(databaseLabel))
                .addGap(51, 51, 51)
                .addComponent(popButton)
                .addGap(18, 18, 18)
                .addComponent(showAllUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showUserButton)
                .addGap(59, 59, 59)
                .addComponent(resetButton)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showAllUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllUserButtonActionPerformed

    private void popButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JButton popButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton selectDBButton;
    private javax.swing.JButton showAllUserButton;
    private javax.swing.JButton showUserButton;
    // End of variables declaration//GEN-END:variables
}
