/*
 * The MIT License
 *
 * Copyright 2017 Neel Patel.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ui.gui.util;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Neel Patel
 */
public class UserDBHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgramDetailCreater
     */
    public UserDBHomePanel() {
        //creditErrLabel.setText("");
        initComponents();    
    }

    public JButton getAddUserButton() {
        return addUserButton;
    }

    public void setAddUserButton(JButton addUserButton) {
        this.addUserButton = addUserButton;
    }

    public JLabel getDatabaseLabel() {
        return databaseLabel;
    }

    public void setDatabaseLabel(JLabel databaseLabel) {
        this.databaseLabel = databaseLabel;
    }

    public JButton getRemoveUserButton() {
        return removeUserButton;
    }

    public void setRemoveUserButton(JButton removeUserButton) {
        this.removeUserButton = removeUserButton;
    }

    public JButton getSelectDBButton() {
        return selectDBButton;
    }

    public void setSelectDBButton(JButton selectDBButton) {
        this.selectDBButton = selectDBButton;
    }

    public JButton getShowUserButton() {
        return showUserButton;
    }

    public void setShowUserButton(JButton showUserButton) {
        this.showUserButton = showUserButton;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databaseLabel = new javax.swing.JLabel();
        selectDBButton = new javax.swing.JButton();
        showUserButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        removeUserButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(9, 238, 249));
        setToolTipText(""); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(100, 17));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        databaseLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        databaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        databaseLabel.setText("none");
        databaseLabel.setToolTipText("");
        databaseLabel.setName("creditLable"); // NOI18N

        selectDBButton.setBackground(new java.awt.Color(0, 0, 0));
        selectDBButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        selectDBButton.setForeground(new java.awt.Color(9, 238, 249));
        selectDBButton.setText("Select DataBase");
        selectDBButton.setBorder(null);

        showUserButton.setBackground(new java.awt.Color(0, 0, 0));
        showUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showUserButton.setForeground(new java.awt.Color(9, 238, 249));
        showUserButton.setText("Show all Users");
        showUserButton.setBorder(null);
        showUserButton.setOpaque(false);

        addUserButton.setBackground(new java.awt.Color(0, 0, 0));
        addUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(9, 238, 249));
        addUserButton.setText("Add new User");
        addUserButton.setBorder(null);
        addUserButton.setOpaque(false);
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        removeUserButton.setBackground(new java.awt.Color(0, 0, 0));
        removeUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removeUserButton.setForeground(new java.awt.Color(255, 102, 0));
        removeUserButton.setText("Remove User");
        removeUserButton.setBorder(null);
        removeUserButton.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectDBButton)
                        .addGap(18, 18, 18)
                        .addComponent(databaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showUserButton)
                            .addComponent(addUserButton)
                            .addComponent(removeUserButton))
                        .addGap(0, 682, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDBButton)
                    .addComponent(databaseLabel))
                .addGap(51, 51, 51)
                .addComponent(showUserButton)
                .addGap(59, 59, 59)
                .addComponent(addUserButton)
                .addGap(59, 59, 59)
                .addComponent(removeUserButton)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JButton removeUserButton;
    private javax.swing.JButton selectDBButton;
    private javax.swing.JButton showUserButton;
    // End of variables declaration//GEN-END:variables
}
